[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[phases.setup]
addedPkgs = ["openssl"]

[start]
cmd = "node .next/standalone/server.js"

[environment]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"
HOSTNAME = "0.0.0.0"
